name: Cross-browser Playwright Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install chromium firefox webkit --with-deps

      - name: Run Safari tests
        run: npx playwright test --project=Safari --output=playwright-report-macos --reporter html

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            playwright-report-macos
            test-results/

  test-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install chromium firefox webkit --with-deps

      - name: Run Edge/Chrome/Firefox/Pixel tests
        run: npx playwright test --project=Edge --project=Chrome --project=Firefox --project=Pixel7 --output=playwright-report-windows --reporter html

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            playwright-report-windows
            test-results/

  merge-reports-and-deploy:
    needs: [test-macos, test-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts
          merge-multiple: true

      - name: Install dependencies
        run: npm ci

      - name: Merge HTML reports
        run: |
          npx playwright merge-reports --reporter html downloaded-artifacts/playwright-report-* > /dev/null
          mv playwright-report merged-report

      - name: Upload merged HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-merged-html-report
          path: merged-report

      - name: Deploy HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: merged-report
